#!/usr/bin/env python3
"""
GUI for annotating an affect_template.csv generated by add_minute_affect.py.

This script does NOT read the raw EEG CSV.
This script does NOT compute timestamps.
This script does NOT merge labels back into EEG rows.

It only opens a template like:

    user_id,session_id,affect_minute,start_sec,end_sec,manual_valence,manual_arousal

You rate each row, then save an annotated template.

Recommended workflow:

1. Generate template:

    python add_minute_affect.py \
        --eeg-csv your_dataset.csv \
        --time-mode timestamp \
        --time-col timestamp \
        --generate-template affect_template.csv

2. Annotate template:

    python rate_minute_affect_gui.py \
        --template affect_template.csv \
        --out affect_template_annotated.csv \
        --scale-min 1 \
        --scale-max 9

3. Merge annotated template:

    python add_minute_affect.py \
        --eeg-csv your_dataset.csv \
        --time-mode timestamp \
        --time-col timestamp \
        --annotations affect_template_annotated.csv \
        --out labeled_dataset.csv
"""

from __future__ import annotations

import argparse
import os
from typing import Optional

import pandas as pd
import tkinter as tk
from tkinter import ttk, messagebox


def is_missing(value) -> bool:
    if pd.isna(value):
        return True
    if isinstance(value, str) and value.strip() == "":
        return True
    return False


def find_column(df: pd.DataFrame, candidates: list[str]) -> Optional[str]:
    """
    Find a column by exact or case-insensitive match.
    """
    exact_cols = set(df.columns)
    lower_to_actual = {c.lower(): c for c in df.columns}

    for candidate in candidates:
        if candidate in exact_cols:
            return candidate

        lowered = candidate.lower()
        if lowered in lower_to_actual:
            return lower_to_actual[lowered]

    return None


def prepare_template_columns(
    df: pd.DataFrame,
    valence_col: str,
    arousal_col: str,
) -> tuple[pd.DataFrame, str, str, str]:
    """
    Ensure the template has:
        affect_minute
        manual_valence
        manual_arousal

    If valence/arousal columns already exist under old names, copy them into
    the requested output names.
    """
    df = df.copy()

    minute_col = find_column(df, ["affect_minute", "minute"])

    if minute_col is None:
        raise ValueError(
            "Template must contain either 'affect_minute' or 'minute'. "
            "Use the template generated by add_minute_affect.py."
        )

    if minute_col != "affect_minute":
        df["affect_minute"] = df[minute_col]
        minute_col = "affect_minute"

    existing_valence = find_column(
        df,
        [valence_col, "manual_valence", "minute_valence", "valence"],
    )

    existing_arousal = find_column(
        df,
        [arousal_col, "manual_arousal", "minute_arousal", "arousal"],
    )

    if valence_col not in df.columns:
        if existing_valence is not None:
            df[valence_col] = df[existing_valence]
        else:
            df[valence_col] = pd.NA

    if arousal_col not in df.columns:
        if existing_arousal is not None:
            df[arousal_col] = df[existing_arousal]
        else:
            df[arousal_col] = pd.NA

    return df, minute_col, valence_col, arousal_col


class AffectTemplateGUI:
    def __init__(
        self,
        df: pd.DataFrame,
        minute_col: str,
        valence_col: str,
        arousal_col: str,
        scale_min: int,
        scale_max: int,
    ) -> None:
        self.df = df.reset_index(drop=True)
        self.minute_col = minute_col
        self.valence_col = valence_col
        self.arousal_col = arousal_col
        self.scale_min = scale_min
        self.scale_max = scale_max

        self.current_idx = 0
        self.loading = False
        self.should_save = False

        self.root = tk.Tk()
        self.root.title("Annotate Affect Template")

        self._build_ui()
        self._update_ui()

        self.root.protocol("WM_DELETE_WINDOW", self._on_close)

    def _build_ui(self) -> None:
        frame = ttk.Frame(self.root, padding=12)
        frame.grid(row=0, column=0, sticky="nsew")

        self.root.columnconfigure(0, weight=1)
        self.root.rowconfigure(0, weight=1)

        self.progress_label = ttk.Label(frame, text="", font=("TkDefaultFont", 12, "bold"))
        self.progress_label.grid(row=0, column=0, columnspan=3, sticky="w", pady=(0, 8))

        self.context_label = ttk.Label(frame, text="", justify="left")
        self.context_label.grid(row=1, column=0, columnspan=3, sticky="w", pady=(0, 12))

        ttk.Label(frame, text="Valence:").grid(row=2, column=0, sticky="w")
        self.valence_scale = ttk.Scale(
            frame,
            from_=self.scale_min,
            to=self.scale_max,
            orient="horizontal",
            command=self._on_valence_change,
        )
        self.valence_scale.grid(row=2, column=1, sticky="ew", padx=(8, 8))
        self.valence_value_label = ttk.Label(frame, text="", width=12)
        self.valence_value_label.grid(row=2, column=2, sticky="w")

        ttk.Label(frame, text="Arousal:").grid(row=3, column=0, sticky="w", pady=(8, 0))
        self.arousal_scale = ttk.Scale(
            frame,
            from_=self.scale_min,
            to=self.scale_max,
            orient="horizontal",
            command=self._on_arousal_change,
        )
        self.arousal_scale.grid(row=3, column=1, sticky="ew", padx=(8, 8), pady=(8, 0))
        self.arousal_value_label = ttk.Label(frame, text="", width=12)
        self.arousal_value_label.grid(row=3, column=2, sticky="w", pady=(8, 0))

        frame.columnconfigure(1, weight=1)

        button_frame = ttk.Frame(frame)
        button_frame.grid(row=4, column=0, columnspan=3, sticky="ew", pady=(14, 0))
        button_frame.columnconfigure((0, 1, 2, 3), weight=1)

        self.prev_button = ttk.Button(button_frame, text="← Previous", command=self._prev)
        self.prev_button.grid(row=0, column=0, sticky="w")

        self.next_button = ttk.Button(button_frame, text="Next →", command=self._next)
        self.next_button.grid(row=0, column=1)

        self.clear_button = ttk.Button(button_frame, text="Clear Current", command=self._clear_current)
        self.clear_button.grid(row=0, column=2)

        self.save_button = ttk.Button(button_frame, text="Save & Exit", command=self._save_and_exit)
        self.save_button.grid(row=0, column=3, sticky="e")

        self.root.bind("<Left>", lambda event: self._prev())
        self.root.bind("<Right>", lambda event: self._next())
        self.root.bind("<Return>", lambda event: self._next())
        self.root.bind("<Command-s>", lambda event: self._save_and_exit())
        self.root.bind("<Control-s>", lambda event: self._save_and_exit())

    def _row_context_text(self, row: pd.Series) -> str:
        parts = []

        if "user_id" in self.df.columns:
            parts.append(f"user_id: {row['user_id']}")

        if "session_id" in self.df.columns:
            parts.append(f"session_id: {row['session_id']}")

        parts.append(f"affect_minute: {row[self.minute_col]}")

        if "start_sec" in self.df.columns and "end_sec" in self.df.columns:
            parts.append(f"time: {float(row['start_sec']):.1f}s – {float(row['end_sec']):.1f}s")

        return "\n".join(parts)

    def _get_numeric_or_none(self, value) -> Optional[int]:
        if is_missing(value):
            return None

        try:
            return int(round(float(value)))
        except ValueError:
            return None
        except TypeError:
            return None

    def _update_ui(self) -> None:
        self.loading = True

        row = self.df.iloc[self.current_idx]

        self.progress_label.config(
            text=f"Template row {self.current_idx + 1} / {len(self.df)}"
        )
        self.context_label.config(text=self._row_context_text(row))

        mid = round((self.scale_min + self.scale_max) / 2)

        existing_valence = self._get_numeric_or_none(row[self.valence_col])
        existing_arousal = self._get_numeric_or_none(row[self.arousal_col])

        valence_display = existing_valence if existing_valence is not None else mid
        arousal_display = existing_arousal if existing_arousal is not None else mid

        self.valence_scale.set(valence_display)
        self.arousal_scale.set(arousal_display)

        if existing_valence is None:
            self.valence_value_label.config(text="not set")
        else:
            self.valence_value_label.config(text=str(existing_valence))

        if existing_arousal is None:
            self.arousal_value_label.config(text="not set")
        else:
            self.arousal_value_label.config(text=str(existing_arousal))

        self.prev_button.config(
            state="disabled" if self.current_idx == 0 else "normal"
        )
        self.next_button.config(
            state="disabled" if self.current_idx == len(self.df) - 1 else "normal"
        )

        self.loading = False

    def _on_valence_change(self, value: str) -> None:
        if self.loading:
            return

        rating = int(round(float(value)))
        self.df.at[self.current_idx, self.valence_col] = rating
        self.valence_value_label.config(text=str(rating))

    def _on_arousal_change(self, value: str) -> None:
        if self.loading:
            return

        rating = int(round(float(value)))
        self.df.at[self.current_idx, self.arousal_col] = rating
        self.arousal_value_label.config(text=str(rating))

    def _prev(self) -> None:
        if self.current_idx > 0:
            self.current_idx -= 1
            self._update_ui()

    def _next(self) -> None:
        if self.current_idx < len(self.df) - 1:
            self.current_idx += 1
            self._update_ui()

    def _clear_current(self) -> None:
        self.df.at[self.current_idx, self.valence_col] = pd.NA
        self.df.at[self.current_idx, self.arousal_col] = pd.NA
        self._update_ui()

    def _missing_rows(self) -> pd.DataFrame:
        missing_mask = (
            self.df[self.valence_col].apply(is_missing)
            | self.df[self.arousal_col].apply(is_missing)
        )
        return self.df[missing_mask]

    def _save_and_exit(self) -> None:
        missing = self._missing_rows()

        if len(missing) > 0:
            preview_cols = [c for c in ["user_id", "session_id", self.minute_col] if c in self.df.columns]
            preview = missing[preview_cols].head(8).to_string(index=False)

            proceed = messagebox.askyesno(
                "Incomplete annotations",
                f"{len(missing)} template rows are still missing valence or arousal.\n\n"
                f"First missing rows:\n{preview}\n\n"
                "Save anyway?"
            )

            if not proceed:
                return

        self.should_save = True
        self.root.quit()

    def _on_close(self) -> None:
        proceed = messagebox.askyesno(
            "Exit",
            "Exit without saving?"
        )

        if proceed:
            self.should_save = False
            self.root.quit()

    def run(self) -> tuple[pd.DataFrame, bool]:
        self.root.mainloop()
        self.root.destroy()
        return self.df, self.should_save


def main() -> None:
    parser = argparse.ArgumentParser(
        description="GUI tool to annotate an affect_template.csv."
    )

    parser.add_argument(
        "--template",
        required=True,
        help="Path to affect_template.csv generated by add_minute_affect.py.",
    )

    parser.add_argument(
        "--out",
        help="Output annotated template path. Default: <template>_annotated.csv",
    )

    parser.add_argument(
        "--scale-min",
        type=int,
        default=1,
        help="Minimum rating value. Default: 1.",
    )

    parser.add_argument(
        "--scale-max",
        type=int,
        default=9,
        help="Maximum rating value. Default: 9.",
    )

    parser.add_argument(
        "--valence-col",
        default="manual_valence",
        help="Valence column to fill. Default: manual_valence.",
    )

    parser.add_argument(
        "--arousal-col",
        default="manual_arousal",
        help="Arousal column to fill. Default: manual_arousal.",
    )

    args = parser.parse_args()

    if args.scale_min >= args.scale_max:
        raise ValueError("--scale-min must be smaller than --scale-max.")

    if not os.path.exists(args.template):
        raise FileNotFoundError(f"Template file not found: {args.template}")

    df = pd.read_csv(args.template)

    df, minute_col, valence_col, arousal_col = prepare_template_columns(
        df=df,
        valence_col=args.valence_col,
        arousal_col=args.arousal_col,
    )

    gui = AffectTemplateGUI(
        df=df,
        minute_col=minute_col,
        valence_col=valence_col,
        arousal_col=arousal_col,
        scale_min=args.scale_min,
        scale_max=args.scale_max,
    )

    annotated_df, should_save = gui.run()

    if not should_save:
        print("Exited without saving.")
        return

    if args.out:
        out_path = args.out
    else:
        base, ext = os.path.splitext(args.template)
        out_path = f"{base}_annotated{ext or '.csv'}"

    annotated_df.to_csv(out_path, index=False)

    print(f"Saved annotated template: {out_path}")
    print(f"Rows: {len(annotated_df)}")
    print(f"Valence column: {valence_col}")
    print(f"Arousal column: {arousal_col}")


if __name__ == "__main__":
    main()